server:
  port: 8066
spring:
  application:
    name: config-client
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    zookeeper:
      connect-string: 'localhost:2181'
      connection-timeout: 1s
      block-until-connected-wait: 1
      max-retries: 1
      discovery:
        root: /discovery
